from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SAMPLE = ROOT / "samples" / "dxf" / "invalid_ship_section.dxf"
DEFAULT_RIGHT_SAMPLE = ROOT / "samples" / "dxf" / "valid_ship_section.dxf"
DEFAULT_OUTPUT_DIR = ROOT / ".run"


class DemoWalkthrough:
    def __init__(self, base_url: str, username: str, password: str, poll_seconds: int) -> None:
        self.base_url = base_url.rstrip("/")
        self.username = username
        self.password = password
        self.poll_seconds = poll_seconds
        self.client = httpx.Client(base_url=self.base_url, timeout=30.0)
        self.headers: dict[str, str] = {}

    def close(self) -> None:
        self.client.close()

    def request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        headers = dict(self.headers)
        headers.update(kwargs.pop("headers", {}))
        response = self.client.request(method, path, headers=headers, **kwargs)
        if response.status_code >= 400:
            try:
                detail = response.json()
            except ValueError:
                detail = response.text
            raise RuntimeError(f"{method} {path} failed with {response.status_code}: {detail}")
        return response

    def login(self) -> None:
        response = self.request("POST", "/api/auth/login", json={"username": self.username, "password": self.password})
        self.headers = {"Authorization": f"Bearer {response.json()['token']}"}

    def create_project(self, stamp: str) -> dict[str, Any]:
        return self.request(
            "POST",
            "/api/projects",
            json={
                "name": f"Demo Walkthrough {stamp}",
                "shipNo": f"DEMO-{stamp}",
                "owner": "Automated Demo",
                "description": "Generated by tools/run_demo_walkthrough.py",
            },
        ).json()

    def create_drawing(self, project_id: str, stamp: str) -> dict[str, Any]:
        return self.request(
            "POST",
            "/api/drawings",
            json={
                "projectId": project_id,
                "drawingNo": f"DEMO-HULL-{stamp}",
                "title": "Demo Hull Section Review",
                "discipline": "Hull Structure",
            },
        ).json()

    def upload_version(self, drawing_id: str, version_no: str, sample: Path) -> dict[str, Any]:
        with sample.open("rb") as file:
            response = self.request(
                "POST",
                "/api/versions/upload",
                data={"drawingId": drawing_id, "versionNo": version_no},
                files={"file": (sample.name, file, "application/dxf")},
            )
        return response.json()

    def file_size(self, version_id: str) -> int:
        response = self.request("GET", f"/api/versions/{version_id}/file")
        return len(response.content)

    def create_review_task(self, version_id: str) -> dict[str, Any]:
        return self.request("POST", "/api/review-tasks", json={"versionId": version_id}).json()

    def wait_for_task(self, task_id: str) -> dict[str, Any]:
        deadline = time.time() + self.poll_seconds
        last_task: dict[str, Any] | None = None
        while time.time() < deadline:
            task = self.request("GET", f"/api/review-tasks/{task_id}").json()
            last_task = task
            if task.get("status") in {"FINISHED", "FAILED"}:
                return task
            time.sleep(1.0)
        raise TimeoutError(f"Review task {task_id} did not finish in {self.poll_seconds}s. Last task={last_task}")

    def task_steps(self, task_id: str) -> list[dict[str, Any]]:
        return self.request("GET", f"/api/review-tasks/{task_id}/steps").json()

    def issues(self, task_id: str) -> list[dict[str, Any]]:
        return self.request("GET", "/api/issues", params={"taskId": task_id}).json()

    def entities(self, version_id: str) -> list[dict[str, Any]]:
        return self.request("GET", f"/api/versions/{version_id}/entities").json()

    def versions(self, drawing_id: str) -> list[dict[str, Any]]:
        return self.request("GET", "/api/versions", params={"drawingId": drawing_id}).json()

    def create_report(self, task_id: str) -> dict[str, Any]:
        return self.request("POST", "/api/reports", json={"taskId": task_id}).json()

    def compare_versions(self, left_id: str, right_id: str) -> dict[str, Any]:
        return self.request("GET", "/api/versions/compare", params={"leftId": left_id, "rightId": right_id}).json()

    def report_download(self, report_id: str) -> dict[str, Any]:
        response = self.request("GET", f"/api/reports/{report_id}/download")
        return {
            "size": len(response.content),
            "contentType": response.headers.get("content-type", ""),
            "contentDisposition": response.headers.get("content-disposition", ""),
        }

    def update_issue(self, issue_id: str, status: str, note: str, report_id: str = "") -> dict[str, Any]:
        return self.request(
            "PATCH",
            f"/api/issues/{issue_id}",
            json={
                "status": status,
                "assignee": "demo-reviewer",
                "note": note,
                "reportId": report_id,
            },
        ).json()

    def remediations(self, issue_id: str) -> list[dict[str, Any]]:
        return self.request("GET", f"/api/issues/{issue_id}/remediations").json()

    def run(
        self,
        sample: Path,
        right_sample: Path,
        version_no: str,
        right_version_no: str,
        output: Path,
    ) -> tuple[dict[str, Any], list[tuple[str, bool]]]:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        self.login()
        project = self.create_project(stamp)
        drawing = self.create_drawing(project["id"], stamp)
        version = self.upload_version(drawing["id"], version_no, sample)
        uploaded_file_size = self.file_size(version["id"])
        task = self.create_review_task(version["id"])
        finished = self.wait_for_task(task["id"])
        steps = self.task_steps(task["id"])
        issues = self.issues(task["id"])
        entities = self.entities(version["id"])
        version_after_parse = self.find_version(drawing["id"], version["id"])
        report = self.create_report(task["id"])
        report_download = self.report_download(report["id"])
        remediation_records: list[dict[str, Any]] = []
        remediated_issue: dict[str, Any] | None = None
        if issues:
            remediated_issue = issues[0]
            self.update_issue(remediated_issue["id"], "IN_PROGRESS", "Demo: remediation started from evidence chain.")
            self.update_issue(remediated_issue["id"], "READY_FOR_REVIEW", "Demo: fix submitted for expert review.")
            self.update_issue(remediated_issue["id"], "CLOSED", "Demo: reviewer accepted the fix and linked the report.", report["id"])
            remediation_records = self.remediations(remediated_issue["id"])
        right_version = self.upload_version(drawing["id"], right_version_no, right_sample)
        right_file_size = self.file_size(right_version["id"])
        right_task = self.create_review_task(right_version["id"])
        right_finished = self.wait_for_task(right_task["id"])
        right_steps = self.task_steps(right_task["id"])
        right_issues = self.issues(right_task["id"])
        right_version_after_parse = self.find_version(drawing["id"], right_version["id"])
        comparison = self.compare_versions(version["id"], right_version["id"])

        checks = acceptance_checks(
            uploaded_file_size,
            finished,
            steps,
            issues,
            report,
            report_download,
            remediation_records,
            right_file_size,
            right_finished,
            right_steps,
            comparison,
        )
        result = {
            "baseUrl": self.base_url,
            "sample": sample,
            "rightSample": right_sample,
            "project": project,
            "drawing": drawing,
            "version": version_after_parse,
            "rightVersion": right_version_after_parse,
            "task": finished,
            "rightTask": right_finished,
            "steps": steps,
            "rightSteps": right_steps,
            "issues": issues,
            "rightIssues": right_issues,
            "entities": entities,
            "report": report,
            "reportDownload": report_download,
            "remediatedIssue": remediated_issue,
            "remediationRecords": remediation_records,
            "comparison": comparison,
            "fileSize": uploaded_file_size,
            "rightFileSize": right_file_size,
        }
        write_summary(output, result, checks)
        return result, checks

    def find_version(self, drawing_id: str, version_id: str) -> dict[str, Any]:
        for version in self.versions(drawing_id):
            if version.get("id") == version_id:
                return version
        raise AssertionError(f"Uploaded version {version_id} was not returned by /api/versions")


def acceptance_checks(
    file_size: int,
    task: dict[str, Any],
    steps: list[dict[str, Any]],
    issues: list[dict[str, Any]],
    report: dict[str, Any],
    report_download: dict[str, Any],
    remediation_records: list[dict[str, Any]],
    right_file_size: int,
    right_task: dict[str, Any],
    right_steps: list[dict[str, Any]],
    comparison: dict[str, Any],
) -> list[tuple[str, bool]]:
    step_status = {step.get("stepCode"): step.get("status") for step in steps}
    right_step_status = {step.get("stepCode"): step.get("status") for step in right_steps}
    issue_evidence_ok = all(issue.get("evidences") for issue in issues) if issues else True
    issue_ai_ok = all((issue.get("aiExplanation") or {}).get("summary") for issue in issues) if issues else True
    remediation_actions = {record.get("action") for record in remediation_records}
    return [
        ("uploaded file endpoint returned content", file_size > 0),
        ("review task finished", task.get("status") == "FINISHED"),
        ("PARSE step succeeded", step_status.get("PARSE") == "SUCCESS"),
        ("RULES step succeeded", step_status.get("RULES") == "SUCCESS"),
        ("visual steps skipped in rule-only demo", step_status.get("RENDER") == "SKIPPED"),
        ("report generated content", bool((report.get("content") or "").strip())),
        ("report download endpoint returned markdown", report_download.get("size", 0) > 0 and "text/markdown" in report_download.get("contentType", "")),
        ("report download endpoint returned attachment", "attachment" in report_download.get("contentDisposition", "")),
        ("issue remediation timeline recorded", not issues or {"START_REMEDIATION", "SUBMIT_FOR_REVIEW", "CLOSE"}.issubset(remediation_actions)),
        ("right version file endpoint returned content", right_file_size > 0),
        ("right version review task finished", right_task.get("status") == "FINISHED"),
        ("right version PARSE step succeeded", right_step_status.get("PARSE") == "SUCCESS"),
        ("right version RULES step succeeded", right_step_status.get("RULES") == "SUCCESS"),
        ("version compare endpoint returned summary", bool((comparison.get("summary") or "").strip())),
        ("issues include evidence chains", issue_evidence_ok),
        ("issues include AI explanations", issue_ai_ok),
    ]


def parse_json(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if not value:
        return {}
    try:
        parsed = json.loads(value)
    except (TypeError, ValueError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = [
        "| " + " | ".join(md_escape(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(md_escape(cell) for cell in row) + " |" for row in rows)
    return "\n".join(lines)


def evidence_types(issue: dict[str, Any]) -> str:
    types = sorted({item.get("evidenceType") for item in issue.get("evidences", []) if item.get("evidenceType")})
    return ", ".join(types)


def short(value: Any, length: int = 10) -> str:
    text = "" if value is None else str(value)
    return text if len(text) <= length else text[:length]


def report_preview(content: str, max_chars: int = 1600) -> str:
    content = content.strip()
    if len(content) <= max_chars:
        return content
    return content[:max_chars].rstrip() + "\n\n... (truncated)"


def write_summary(output: Path, result: dict[str, Any], checks: list[tuple[str, bool]]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    version = result["version"]
    task = result["task"]
    report = result["report"]
    comparison = result["comparison"]
    summary = parse_json(version.get("parseSummaryJson"))
    right_summary = parse_json(result["rightVersion"].get("parseSummaryJson"))
    type_counts = summary.get("typeCounts") or {}
    layers = summary.get("layers") or []
    blocks = summary.get("blocks") or []

    check_rows = [[name, "PASS" if ok else "FAIL"] for name, ok in checks]
    step_rows = [
        [
            step.get("stepOrder"),
            step.get("stepCode"),
            step.get("stepName"),
            step.get("status"),
            step.get("message") or "",
        ]
        for step in sorted(result["steps"], key=lambda item: item.get("stepOrder", 0))
    ]
    issue_rows = [
        [
            short(issue.get("id")),
            issue.get("ruleCode"),
            issue.get("severity"),
            issue.get("status"),
            issue.get("layerName") or "",
            short(issue.get("entityRef")),
            evidence_types(issue),
            (issue.get("aiExplanation") or {}).get("summary") or "",
        ]
        for issue in result["issues"]
    ]
    entity_rows = [
        [entity_type, count]
        for entity_type, count in sorted(type_counts.items(), key=lambda item: str(item[0]))
    ]

    content = "\n\n".join(
        [
            "# ShipCAD Demo Walkthrough",
            f"- Generated at: {datetime.now(timezone.utc).isoformat()}",
            f"- Backend: {result['baseUrl']}",
            f"- Sample: `{result['sample']}`",
            f"- Right sample: `{result['rightSample']}`",
            f"- File endpoint size: {result['fileSize']} bytes",
            f"- Right file endpoint size: {result['rightFileSize']} bytes",
            f"- Report download size: {result['reportDownload']['size']} bytes",
            "## Created Records\n"
            + md_table(
                ["Record", "ID", "Key Info"],
                [
                    ["Project", result["project"].get("id"), result["project"].get("name")],
                    ["Drawing", result["drawing"].get("id"), result["drawing"].get("drawingNo")],
                    ["Version", version.get("id"), f"{version.get('versionNo')} / {version.get('fileName')}"],
                    ["ReviewTask", task.get("id"), f"{task.get('status')} / stage={task.get('stage')} / issues={task.get('issueCount')}"],
                    ["RightVersion", result["rightVersion"].get("id"), f"{result['rightVersion'].get('versionNo')} / {result['rightVersion'].get('fileName')}"],
                    ["RightReviewTask", result["rightTask"].get("id"), f"{result['rightTask'].get('status')} / stage={result['rightTask'].get('stage')} / issues={result['rightTask'].get('issueCount')}"],
                    ["Report", report.get("id"), f"taskId={report.get('taskId')}"],
                ],
            ),
            "## Acceptance Checks\n" + md_table(["Check", "Result"], check_rows),
            "## Parser Summary\n"
            + md_table(
                ["Metric", "Left", "Right"],
                [
                    ["parseStatus", version.get("parseStatus"), result["rightVersion"].get("parseStatus")],
                    ["entityCount", summary.get("entityCount"), right_summary.get("entityCount")],
                    ["layerCount", len(layers), len(right_summary.get("layers") or [])],
                    ["layers", ", ".join(layers[:20]), ", ".join((right_summary.get("layers") or [])[:20])],
                    ["blocks", ", ".join(blocks[:20]), ", ".join((right_summary.get("blocks") or [])[:20])],
                ],
            ),
            "## Version Compare\n"
            + md_table(
                ["Metric", "Value"],
                [
                    ["summary", comparison.get("summary")],
                    ["entityCountDelta", comparison.get("entityCountDelta")],
                    ["addedLayers", ", ".join(comparison.get("addedLayers") or [])],
                    ["removedLayers", ", ".join(comparison.get("removedLayers") or [])],
                    ["addedTexts", ", ".join(comparison.get("addedTexts") or [])],
                    ["removedTexts", ", ".join(comparison.get("removedTexts") or [])],
                    ["riskHints", " / ".join(comparison.get("riskHints") or [])],
                    ["reviewFocus", " / ".join(comparison.get("reviewFocus") or [])],
                ],
            ),
            "## Remediation Timeline\n"
            + (
                md_table(
                    ["Action", "From", "To", "Assignee", "Report", "Note"],
                    [
                        [
                            record.get("action"),
                            record.get("fromStatus"),
                            record.get("toStatus"),
                            record.get("assignee") or "",
                            record.get("reportId") or "",
                            record.get("note") or "",
                        ]
                        for record in result["remediationRecords"]
                    ],
                )
                if result["remediationRecords"]
                else "No remediation records were generated."
            ),
            "## Entity Type Counts\n" + md_table(["Entity Type", "Count"], entity_rows),
            "## Review Task Steps\n" + md_table(["Order", "Code", "Name", "Status", "Message"], step_rows),
            "## Issues\n"
            + (
                md_table(["ID", "Rule", "Severity", "Status", "Layer", "EntityRef", "Evidence Types", "AI Summary"], issue_rows)
                if issue_rows
                else "No issues were generated."
            ),
            "## Report Preview\n\n```markdown\n" + report_preview(report.get("content") or "") + "\n```",
        ]
    )
    output.write_text(content + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run one live ShipCAD demo walkthrough and write a Markdown summary with created IDs, "
            "task steps, issues, evidence types, parser summary, and report preview."
        )
    )
    parser.add_argument("--base-url", default="http://127.0.0.1:8080", help="Spring Boot API base URL")
    parser.add_argument("--username", default="admin")
    parser.add_argument("--password", default="admin123")
    parser.add_argument("--sample", type=Path, default=DEFAULT_SAMPLE, help="DXF sample used for the walkthrough")
    parser.add_argument("--right-sample", type=Path, default=DEFAULT_RIGHT_SAMPLE, help="Second DXF sample used for version comparison")
    parser.add_argument("--version-no", default="V1")
    parser.add_argument("--right-version-no", default="V2")
    parser.add_argument("--poll-seconds", type=int, default=45)
    parser.add_argument("--output", type=Path, help="Markdown output path")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sample = args.sample.resolve()
    if not sample.exists():
        print(f"DXF sample not found: {sample}", file=sys.stderr)
        return 2
    right_sample = args.right_sample.resolve()
    if not right_sample.exists():
        print(f"Right DXF sample not found: {right_sample}", file=sys.stderr)
        return 2
    output = args.output
    if output is None:
        stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        output = DEFAULT_OUTPUT_DIR / f"demo-walkthrough-{stamp}.md"
    output = output.resolve()

    runner = DemoWalkthrough(args.base_url, args.username, args.password, args.poll_seconds)
    try:
        result, checks = runner.run(sample, right_sample, args.version_no, args.right_version_no, output)
    except Exception as exc:
        print(f"Demo walkthrough failed: {exc}", file=sys.stderr)
        return 1
    finally:
        runner.close()

    failed = [name for name, ok in checks if not ok]
    print("\nShipCAD demo walkthrough")
    print("-" * 88)
    print(f"Project ID : {result['project']['id']}")
    print(f"Drawing ID : {result['drawing']['id']}")
    print(f"Version ID : {result['version']['id']}")
    print(f"Task ID    : {result['task']['id']} ({result['task']['status']})")
    print(f"Right ID   : {result['rightVersion']['id']}")
    print(f"Right Task : {result['rightTask']['id']} ({result['rightTask']['status']})")
    print(f"Report ID  : {result['report']['id']}")
    print(f"Issues     : {len(result['issues'])}")
    print(f"Remediation: {len(result['remediationRecords'])} records")
    print(f"Compare    : {result['comparison']['summary']}")
    print(f"Summary    : {output}")
    print("-" * 88)
    if failed:
        print(f"Failed checks: {failed}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
