from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from typing import Any

import httpx


class AccessControlE2E:
    def __init__(self, base_url: str) -> None:
        self.client = httpx.Client(base_url=base_url.rstrip("/"), timeout=30.0)

    def close(self) -> None:
        self.client.close()

    def login(self, username: str, password: str) -> tuple[dict[str, str], dict[str, Any]]:
        response = self.client.post("/api/auth/login", json={"username": username, "password": password})
        self.expect_status(response, 200)
        payload = response.json()
        return {"Authorization": f"Bearer {payload['token']}"}, payload

    def expect_status(self, response: httpx.Response, expected: int) -> None:
        if response.status_code != expected:
            raise AssertionError(
                f"{response.request.method} {response.request.url.path} returned "
                f"{response.status_code}, expected {expected}: {response.text}"
            )

    def run(self) -> None:
        admin, admin_login = self.login("admin", "admin123")
        expert, expert_login = self.login("expert", "expert123")
        engineer, engineer_login = self.login("engineer", "engineer123")
        viewer, viewer_login = self.login("viewer", "viewer123")

        self.assert_role(admin, admin_login, "ADMIN", "AUDIT_VIEW")
        self.assert_role(expert, expert_login, "REVIEW_EXPERT", "REVIEW_EXECUTE")
        self.assert_role(engineer, engineer_login, "DESIGN_ENGINEER", "VERSION_UPLOAD")
        self.assert_role(viewer, viewer_login, "VIEWER", None)

        self.expect_status(self.client.get("/api/projects", headers=viewer), 200)
        self.expect_status(
            self.client.post(
                "/api/projects",
                headers=viewer,
                json={"name": "forbidden-viewer", "shipNo": "", "owner": "", "description": ""},
            ),
            403,
        )
        self.expect_status(
            self.client.post(
                "/api/projects",
                headers=expert,
                json={"name": "forbidden-expert", "shipNo": "", "owner": "", "description": ""},
            ),
            403,
        )

        stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        project_response = self.client.post(
            "/api/projects",
            headers=engineer,
            json={
                "name": f"Access Control E2E {stamp}",
                "shipNo": f"RBAC-{stamp}",
                "owner": "Automated Acceptance",
                "description": "Generated by tools/run_access_control_e2e.py",
            },
        )
        self.expect_status(project_response, 200)
        engineer_project = project_response.json()

        viewer_projects = self.client.get("/api/projects", headers=viewer)
        self.expect_status(viewer_projects, 200)
        if engineer_project["id"] in {project["id"] for project in viewer_projects.json()}:
            raise AssertionError("viewer can see an unassigned engineer project")
        self.expect_status(
            self.client.get(
                "/api/drawings",
                headers=viewer,
                params={"projectId": engineer_project["id"]},
            ),
            403,
        )

        viewer_user = next(
            user for user in self.client.get("/api/users", headers=admin).json()
            if user["username"] == "viewer"
        )
        add_member = self.client.post(
            f"/api/projects/{engineer_project['id']}/members",
            headers=admin,
            json={"userId": viewer_user["id"]},
        )
        self.expect_status(add_member, 200)
        assigned_projects = self.client.get("/api/projects", headers=viewer)
        self.expect_status(assigned_projects, 200)
        if engineer_project["id"] not in {project["id"] for project in assigned_projects.json()}:
            raise AssertionError("viewer cannot see a project after membership assignment")
        self.expect_status(
            self.client.get(
                "/api/drawings",
                headers=viewer,
                params={"projectId": engineer_project["id"]},
            ),
            200,
        )
        self.expect_status(
            self.client.delete(
                f"/api/projects/{engineer_project['id']}/members/{viewer_user['id']}",
                headers=admin,
            ),
            200,
        )
        self.expect_status(
            self.client.get(
                "/api/drawings",
                headers=viewer,
                params={"projectId": engineer_project["id"]},
            ),
            403,
        )

        self.expect_status(
            self.client.post(
                "/api/review-tasks",
                headers=engineer,
                json={"versionId": "permission-check-before-domain-validation"},
            ),
            403,
        )
        self.expect_status(self.client.get("/api/audit-logs", headers=engineer), 403)

        audit_response = self.client.get(
            "/api/audit-logs",
            headers=admin,
            params={"action": "ACCESS_DENIED", "targetType": "permission", "size": 100},
        )
        self.expect_status(audit_response, 200)
        denied = audit_response.json()["items"]
        denied_actors = {item["actor"] for item in denied}
        expected_actors = {"viewer", "expert", "engineer"}
        if not expected_actors.issubset(denied_actors):
            raise AssertionError(
                f"audit log is missing denied actors: expected {sorted(expected_actors)}, "
                f"actual {sorted(denied_actors)}"
            )

        project_audit = self.client.get(
            "/api/audit-logs",
            headers=admin,
            params={"actor": "engineer", "action": "PROJECT_CREATE", "targetType": "project"},
        )
        self.expect_status(project_audit, 200)
        if not project_audit.json()["items"]:
            raise AssertionError("engineer project creation was not written to the audit log")

        identity_stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S%f")
        managed_username = f"e2e_user_{identity_stamp}"
        initial_password = "IdentityPassword123"
        changed_password = "IdentityPassword456"
        create_user = self.client.post(
            "/api/users",
            headers=admin,
            json={
                "username": managed_username,
                "displayName": "Identity E2E User",
                "role": "DESIGN_ENGINEER",
                "password": initial_password,
                "enabled": True,
            },
        )
        self.expect_status(create_user, 200)
        managed_user = create_user.json()
        managed_headers, _ = self.login(managed_username, initial_password)
        self.expect_status(self.client.get("/api/auth/me", headers=managed_headers), 200)

        change_password = self.client.post(
            "/api/auth/change-password",
            headers=managed_headers,
            json={"currentPassword": initial_password, "newPassword": changed_password},
        )
        self.expect_status(change_password, 200)
        self.expect_status(self.client.get("/api/auth/me", headers=managed_headers), 401)
        self.expect_status(
            self.client.post("/api/auth/login", json={"username": managed_username, "password": initial_password}),
            401,
        )
        changed_headers, _ = self.login(managed_username, changed_password)

        disable_user = self.client.patch(
            f"/api/users/{managed_user['id']}",
            headers=admin,
            json={"displayName": "Identity E2E User", "role": "DESIGN_ENGINEER", "enabled": False},
        )
        self.expect_status(disable_user, 200)
        self.expect_status(self.client.get("/api/auth/me", headers=changed_headers), 401)
        self.expect_status(
            self.client.post("/api/auth/login", json={"username": managed_username, "password": changed_password}),
            401,
        )

        logout_username = f"e2e_logout_{identity_stamp}"
        logout_user = self.client.post(
            "/api/users",
            headers=admin,
            json={
                "username": logout_username,
                "displayName": "Logout E2E User",
                "role": "VIEWER",
                "password": initial_password,
                "enabled": True,
            },
        )
        self.expect_status(logout_user, 200)
        logout_headers, _ = self.login(logout_username, initial_password)
        self.expect_status(self.client.post("/api/auth/logout", headers=logout_headers), 200)
        self.expect_status(self.client.get("/api/auth/me", headers=logout_headers), 401)

        print("Access-control E2E passed.")
        print("- viewer: read-only access confirmed")
        print("- design engineer: project authoring allowed, review execution denied")
        print("- review expert: review capability present, project authoring denied")
        print("- admin: audit query and denied-attempt traceability confirmed")
        print("- project scope: membership grant/removal and cross-project denial confirmed")
        print("- identity: user creation, password rotation, disable and logout revocation confirmed")

    def assert_role(
        self,
        headers: dict[str, str],
        login_payload: dict[str, Any],
        expected_role: str,
        expected_permission: str | None,
    ) -> None:
        if login_payload["user"]["role"] != expected_role:
            raise AssertionError(f"login role mismatch for {expected_role}: {login_payload}")
        me = self.client.get("/api/auth/me", headers=headers)
        self.expect_status(me, 200)
        profile = me.json()
        if profile["user"]["role"] != expected_role:
            raise AssertionError(f"/api/auth/me role mismatch for {expected_role}: {profile}")
        permissions = set(profile["permissions"])
        if expected_permission is not None and expected_permission not in permissions:
            raise AssertionError(f"{expected_role} is missing permission {expected_permission}")
        if expected_role == "VIEWER" and permissions:
            raise AssertionError(f"VIEWER should not have write permissions: {sorted(permissions)}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate ShipCAD role permissions and audit logging.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8080")
    args = parser.parse_args()

    suite = AccessControlE2E(args.base_url)
    try:
        suite.run()
        return 0
    except (AssertionError, httpx.HTTPError) as error:
        print(f"Access-control E2E failed: {error}", file=sys.stderr)
        return 1
    finally:
        suite.close()


if __name__ == "__main__":
    raise SystemExit(main())
