import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  DEFAULT_RUN_DIR,
  CdpSession,
  analyzePng,
  apiJson,
  browserTarget,
  delay,
  frontendUrlWithSmokeFlag,
  launchBrowser,
  readCanvasPixels,
  waitFor,
} from './run_dxf_viewer_webgl_smoke.mjs'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const ROOT = path.resolve(__dirname, '..')
const DEFAULT_SAMPLE = path.join(ROOT, 'datasets', 'rules', 'cases', 'invalid_layer_name.dxf')

function parseArgs(argv) {
  const args = {
    backendUrl: 'http://127.0.0.1:8080',
    frontendUrl: 'http://127.0.0.1:5173',
    username: 'admin',
    password: 'admin123',
    sample: DEFAULT_SAMPLE,
    browserPath: process.env.BROWSER_PATH || '',
    browserDebugPort: 9334,
    timeoutMs: 60000,
    minForegroundPixels: 300,
    minForegroundRatio: 0.001,
    minUniqueSampleColors: 3,
    minRedPixels: 6,
    minRedPixelIncrease: 3,
    output: path.join(DEFAULT_RUN_DIR, 'dxf-viewer-issue-focus-smoke.json'),
    screenshot: path.join(DEFAULT_RUN_DIR, 'dxf-viewer-issue-focus-smoke.png'),
    headed: false,
  }
  for (let index = 0; index < argv.length; index += 1) {
    const item = argv[index]
    const next = () => {
      index += 1
      if (index >= argv.length) throw new Error(`${item} requires a value`)
      return argv[index]
    }
    if (item === '--backend-url') args.backendUrl = next()
    else if (item === '--frontend-url') args.frontendUrl = next()
    else if (item === '--username') args.username = next()
    else if (item === '--password') args.password = next()
    else if (item === '--sample') args.sample = path.resolve(next())
    else if (item === '--browser-path') args.browserPath = next()
    else if (item === '--browser-debug-port') args.browserDebugPort = Number(next())
    else if (item === '--timeout-ms') args.timeoutMs = Number(next())
    else if (item === '--min-foreground-pixels') args.minForegroundPixels = Number(next())
    else if (item === '--min-foreground-ratio') args.minForegroundRatio = Number(next())
    else if (item === '--min-unique-sample-colors') args.minUniqueSampleColors = Number(next())
    else if (item === '--min-red-pixels') args.minRedPixels = Number(next())
    else if (item === '--min-red-pixel-increase') args.minRedPixelIncrease = Number(next())
    else if (item === '--output') args.output = path.resolve(next())
    else if (item === '--screenshot') args.screenshot = path.resolve(next())
    else if (item === '--headed') args.headed = true
    else if (item === '--help') {
      printHelp()
      process.exit(0)
    } else {
      throw new Error(`Unknown argument: ${item}`)
    }
  }
  return args
}

function printHelp() {
  console.log(`Usage: node tools/run_dxf_viewer_issue_focus_smoke.mjs [options]

Options:
  --backend-url URL                  Backend API URL. Default: http://127.0.0.1:8080
  --frontend-url URL                 Vue frontend URL. Default: http://127.0.0.1:5173
  --sample PATH                      DXF sample with a focusable review issue.
                                      Default: datasets/rules/cases/invalid_layer_name.dxf
  --browser-path PATH                Chrome/Edge/Chromium executable. Can also use BROWSER_PATH.
  --browser-debug-port PORT          DevTools port. Default: 9334
  --headed                           Run a visible browser instead of headless.
  --output PATH                      JSON report path. Default: .run/dxf-viewer-issue-focus-smoke.json
  --screenshot PATH                  Focused canvas PNG path. Default: .run/dxf-viewer-issue-focus-smoke.png
  --min-red-pixels N                 Minimum red highlight pixels after focus. Default: 6
  --min-red-pixel-increase N         Minimum red pixel increase after issue click. Default: 3
`)
}

async function createFocusedReview(args) {
  const baseUrl = args.backendUrl.replace(/\/$/, '')
  const stamp = new Date().toISOString().replace(/\D/g, '').slice(0, 14)
  const runId = `${stamp}-${crypto.randomBytes(3).toString('hex')}`
  const login = await apiJson(baseUrl, '/api/auth/login', '', {
    method: 'POST',
    body: JSON.stringify({ username: args.username, password: args.password }),
  })
  const token = login.token
  const project = await apiJson(baseUrl, '/api/projects', token, {
    method: 'POST',
    body: JSON.stringify({
      name: `DXF Issue Focus Smoke ${runId}`,
      shipNo: `FOCUS-${runId}`,
      owner: 'Automated Smoke',
      description: 'Generated by tools/run_dxf_viewer_issue_focus_smoke.mjs',
    }),
  })
  const drawing = await apiJson(baseUrl, '/api/drawings', token, {
    method: 'POST',
    body: JSON.stringify({
      projectId: project.id,
      drawingNo: 'GOLDEN-INVALID_LAYER_NAME',
      title: 'Invalid Layer Name',
      discipline: 'Hull Structure',
    }),
  })

  const form = new FormData()
  const sampleBytes = await fs.promises.readFile(args.sample)
  form.set('drawingId', drawing.id)
  form.set('versionNo', 'V1')
  form.set('file', new Blob([sampleBytes], { type: 'application/dxf' }), path.basename(args.sample))
  const version = await apiJson(baseUrl, '/api/versions/upload', token, { method: 'POST', body: form })
  const task = await apiJson(baseUrl, '/api/review-tasks', token, {
    method: 'POST',
    body: JSON.stringify({ versionId: version.id }),
  })
  const finishedTask = await waitForTask(baseUrl, token, task.id, args.timeoutMs)
  if (finishedTask.status !== 'FINISHED') {
    throw new Error(`Review task failed: ${finishedTask.errorMessage ?? 'unknown error'}`)
  }
  const issues = await apiJson(baseUrl, `/api/issues?taskId=${encodeURIComponent(task.id)}`, token)
  if (!issues.length) throw new Error(`Review task ${task.id} produced no issues`)
  const selectedIssue = issues.find(hasFocusableLocation) ?? issues[0]
  if (!hasFocusableLocation(selectedIssue)) {
    throw new Error(`Review task ${task.id} produced no focusable issue evidence`)
  }
  const entities = await apiJson(baseUrl, `/api/versions/${encodeURIComponent(version.id)}/entities`, token)
  return { token, project, drawing, version, task: finishedTask, issues, selectedIssue, entityCount: entities.length }
}

async function waitForTask(baseUrl, token, taskId, timeoutMs) {
  return waitFor(async () => {
    const task = await apiJson(baseUrl, `/api/review-tasks/${encodeURIComponent(taskId)}`, token)
    return task.status === 'FINISHED' || task.status === 'FAILED' ? task : null
  }, timeoutMs, 1000)
}

function hasFocusableLocation(issue) {
  if (issue.entityRef || issue.layerName) return true
  return (issue.evidences ?? []).some((evidence) => {
    const location = evidence.location
    if (!location?.bounds) return false
    return location.coordinateSpace === 'CAD_MODEL' || location.transform?.targetSpace === 'CAD_MODEL'
  })
}

async function runIssueFocusSmoke(args, token, versionId, issue) {
  const launched = launchBrowser(args)
  const frontendSmokeUrl = frontendUrlWithSmokeFlag(args.frontendUrl)
  let cdp
  try {
    const target = await browserTarget(args.browserDebugPort, args.timeoutMs)
    cdp = await CdpSession.connect(target.webSocketDebuggerUrl)
    await cdp.send('Page.enable')
    await cdp.send('Runtime.enable')
    await cdp.send('Page.navigate', { url: frontendSmokeUrl })
    await waitFor(() => cdp.evaluate('document.readyState === "complete" || document.readyState === "interactive"'), args.timeoutMs)
    await cdp.evaluate(`localStorage.setItem('shipcad_token', ${JSON.stringify(token)}); location.reload()`)
    await waitFor(() => cdp.evaluate('document.readyState === "complete" || document.readyState === "interactive"'), args.timeoutMs)
    await waitFor(() => cdp.evaluate(`document.body && document.body.textContent.includes('已登录')`), args.timeoutMs)
    const switched = await cdp.evaluate(`(() => {
      const button = Array.from(document.querySelectorAll('button')).find((item) => item.textContent.trim() === '问题闭环')
      if (!button) return false
      button.click()
      return true
    })()`)
    if (!switched) throw new Error('Could not find 问题闭环 navigation button')

    await selectPreviewVersion(cdp, versionId, args.timeoutMs)
    const readyState = await waitForViewerReady(cdp, args.timeoutMs)
    await cdp.evaluate(`document.querySelector('.dxf-webgl-host')?.scrollIntoView({ block: 'center', inline: 'center' })`)
    await delay(500)
    await cdp.evaluate(`document.querySelector('.viewer-tools button')?.click()`)
    await delay(500)
    const beforeFocus = await readRedPixels(cdp)
    const beforeCanvas = await readCanvasPixels(cdp)
    assertCanvasVisible(beforeCanvas, args)

    const clicked = await cdp.evaluate(`(() => {
      const issue = Array.from(document.querySelectorAll('.issue')).find((item) => item.getAttribute('data-issue-id') === ${JSON.stringify(issue.id)})
      if (!issue) {
        return {
          ok: false,
          issueCount: document.querySelectorAll('.issue').length,
          issueIds: Array.from(document.querySelectorAll('.issue')).map((item) => item.getAttribute('data-issue-id')).slice(0, 10)
        }
      }
      issue.scrollIntoView({ block: 'center', inline: 'nearest' })
      issue.click()
      return { ok: true }
    })()`)
    if (!clicked?.ok) throw new Error(`Could not click target issue: ${JSON.stringify(clicked)}`)

    const focusState = await waitFor(async () => {
      const value = await cdp.evaluate(`(() => {
        const meta = document.querySelector('.dxf-meta')?.textContent || ''
        const error = document.querySelector('.viewer-error')?.textContent || ''
        const hint = document.querySelector('.dxf-meta .focus-hint')?.textContent || ''
        const selected = document.querySelector('.issue.selected')
        return {
          ready: meta.includes('已聚焦问题') && hint && !hint.includes('暂无') && selected?.getAttribute('data-issue-id') === ${JSON.stringify(issue.id)} && !error,
          meta,
          hint,
          error,
          selectedIssueId: selected?.getAttribute('data-issue-id') || ''
        }
      })()`)
      return value?.ready ? value : null
    }, args.timeoutMs, 500)
    await delay(1000)
    const afterFocus = await readRedPixels(cdp)
    const afterCanvas = await readCanvasPixels(cdp)
    assertCanvasVisible(afterCanvas, args)
    const redIncrease = afterFocus.redPixels - beforeFocus.redPixels
    if (afterFocus.redPixels < args.minRedPixels || redIncrease < args.minRedPixelIncrease) {
      throw new Error(`Selected issue highlight did not produce enough red pixels: ${JSON.stringify({ beforeFocus, afterFocus, redIncrease })}`)
    }

    const screenshotDataUrl = await cdp.evaluate(`(() => {
      const canvas = document.querySelector('.dxf-webgl-host canvas')
      if (!canvas) return ''
      return canvas.toDataURL('image/png')
    })()`)
    if (!screenshotDataUrl.startsWith('data:image/png;base64,')) {
      throw new Error('Focused preview canvas did not produce a PNG data URL')
    }
    const screenshotBytes = Buffer.from(screenshotDataUrl.slice('data:image/png;base64,'.length), 'base64')
    await fs.promises.mkdir(path.dirname(args.screenshot), { recursive: true })
    await fs.promises.writeFile(args.screenshot, screenshotBytes)
    const pixels = analyzePng(screenshotBytes)
    assertCanvasVisible(pixels, args)
    return {
      readyState,
      focusState,
      beforeFocus,
      afterFocus,
      redIncrease,
      beforeCanvas,
      afterCanvas,
      screenshot: args.screenshot,
      pixels,
    }
  } finally {
    if (cdp) cdp.close()
    launched.processHandle.kill()
    await new Promise((resolve) => {
      const timer = setTimeout(resolve, 1000)
      launched.processHandle.once('exit', () => {
        clearTimeout(timer)
        resolve()
      })
    })
    await fs.promises.rm(launched.profileDir, { recursive: true, force: true }).catch(() => undefined)
  }
}

async function selectPreviewVersion(cdp, versionId, timeoutMs) {
  let lastSelection = null
  await waitFor(async () => {
    lastSelection = await cdp.evaluate(`(() => {
      const select = document.querySelector('.preview-panel select')
      if (!select) return { ok: false, reason: 'missing preview select' }
      const option = Array.from(select.options).find((item) => item.value === ${JSON.stringify(versionId)})
      if (!option) return { ok: false, reason: 'version option missing', optionCount: select.options.length }
      select.value = ${JSON.stringify(versionId)}
      select.dispatchEvent(new Event('change', { bubbles: true }))
      return { ok: true, optionCount: select.options.length }
    })()`)
    return lastSelection?.ok ? lastSelection : null
  }, timeoutMs, 500).catch((error) => {
    throw new Error(`Could not select smoke version: ${JSON.stringify(lastSelection)}; ${error.message}`)
  })
}

async function waitForViewerReady(cdp, timeoutMs) {
  return waitFor(async () => {
    const value = await cdp.evaluate(`(() => {
      const meta = document.querySelector('.dxf-meta')?.textContent || ''
      const error = document.querySelector('.viewer-error')?.textContent || ''
      const host = document.querySelector('.dxf-webgl-host')
      const canvas = host?.querySelector('canvas')
      const layers = Array.from(document.querySelectorAll('.dxf-meta .layer-row span')).map((item) => item.textContent || '')
      return {
        ready: meta.includes('dxf-viewer') && meta.includes('加载完成') && Boolean(canvas) && canvas.width > 0 && canvas.height > 0 && layers.length > 0 && !error,
        meta,
        error,
        layerCount: layers.length,
        layers,
        hasHost: Boolean(host),
        hasCanvas: Boolean(canvas),
        canvasWidth: canvas?.width ?? 0,
        canvasHeight: canvas?.height ?? 0
      }
    })()`)
    return value?.ready ? value : null
  }, timeoutMs, 500)
}

function assertCanvasVisible(pixels, args) {
  if (
    pixels.foregroundPixels < args.minForegroundPixels ||
    pixels.foregroundRatio < args.minForegroundRatio ||
    pixels.uniqueSampleColors < args.minUniqueSampleColors
  ) {
    throw new Error(`Preview canvas appears blank: ${JSON.stringify(pixels)}`)
  }
}

async function readRedPixels(cdp) {
  return cdp.evaluate(`(() => {
    const canvas = document.querySelector('.dxf-webgl-host canvas')
    if (!canvas) return { ok: false, reason: 'missing canvas', redPixels: 0 }
    const gl = canvas.getContext('webgl2') || canvas.getContext('webgl') || canvas.getContext('experimental-webgl')
    if (!gl) return { ok: false, reason: 'missing webgl context', width: canvas.width, height: canvas.height, redPixels: 0 }
    gl.finish()
    const width = gl.drawingBufferWidth
    const height = gl.drawingBufferHeight
    const data = new Uint8Array(width * height * 4)
    gl.readPixels(0, 0, width, height, gl.RGBA, gl.UNSIGNED_BYTE, data)
    let redPixels = 0
    let strongestRed = 0
    for (let offset = 0; offset < data.length; offset += 4) {
      const r = data[offset]
      const g = data[offset + 1]
      const b = data[offset + 2]
      const redScore = r - Math.max(g, b)
      if (r >= 140 && redScore >= 45) redPixels += 1
      if (redScore > strongestRed) strongestRed = redScore
    }
    const pixels = width * height
    return {
      ok: true,
      width,
      height,
      pixels,
      redPixels,
      redPixelRatio: Number((redPixels / pixels).toFixed(8)),
      strongestRed
    }
  })()`)
}

async function main() {
  const args = parseArgs(process.argv.slice(2))
  fs.mkdirSync(DEFAULT_RUN_DIR, { recursive: true })
  if (!fs.existsSync(args.sample)) throw new Error(`DXF sample does not exist: ${args.sample}`)
  const sampleHash = crypto.createHash('sha256').update(await fs.promises.readFile(args.sample)).digest('hex')
  const created = await createFocusedReview(args)
  const browser = await runIssueFocusSmoke(args, created.token, created.version.id, created.selectedIssue)
  const report = {
    ok: true,
    time: new Date().toISOString(),
    backendUrl: args.backendUrl,
    frontendUrl: args.frontendUrl,
    sample: args.sample,
    sampleSha256: sampleHash,
    projectId: created.project.id,
    drawingId: created.drawing.id,
    versionId: created.version.id,
    taskId: created.task.id,
    taskStatus: created.task.status,
    issueCount: created.issues.length,
    selectedIssue: {
      id: created.selectedIssue.id,
      ruleCode: created.selectedIssue.ruleCode,
      layerName: created.selectedIssue.layerName,
      entityRef: created.selectedIssue.entityRef,
      evidenceTypes: (created.selectedIssue.evidences ?? []).map((evidence) => evidence.evidenceType),
    },
    entityCount: created.entityCount,
    viewer: browser,
  }
  await fs.promises.mkdir(path.dirname(args.output), { recursive: true })
  await fs.promises.writeFile(args.output, JSON.stringify(report, null, 2) + '\n', 'utf8')
  console.log(`DXF issue focus smoke passed: issue=${created.selectedIssue.id} rule=${created.selectedIssue.ruleCode} redIncrease=${browser.redIncrease}`)
  console.log(`Report: ${args.output}`)
  console.log(`Screenshot: ${args.screenshot}`)
}

async function writeFailureReport(error) {
  const outputArg = process.argv.findIndex((item) => item === '--output')
  const output = outputArg >= 0 && process.argv[outputArg + 1] ? path.resolve(process.argv[outputArg + 1]) : path.join(DEFAULT_RUN_DIR, 'dxf-viewer-issue-focus-smoke.json')
  await fs.promises.mkdir(path.dirname(output), { recursive: true }).catch(() => undefined)
  await fs.promises.writeFile(output, JSON.stringify({ ok: false, error: error.message, time: new Date().toISOString() }, null, 2) + '\n', 'utf8').catch(() => undefined)
  console.error(`DXF issue focus smoke failed: ${error.message}`)
  process.exit(1)
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  main().catch(writeFailureReport)
}
