from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VALID_SAMPLE = ROOT / "datasets" / "rules" / "cases" / "compliant_section.dxf"
DEFAULT_OUTPUT_DIR = ROOT / ".run" / "task-retry-e2e"


@dataclass
class Check:
    name: str
    ok: bool
    detail: str = ""


class TaskRetryE2E:
    def __init__(self, base_url: str, username: str, password: str, poll_seconds: int, run_dir: Path) -> None:
        self.base_url = base_url.rstrip("/")
        self.username = username
        self.password = password
        self.poll_seconds = poll_seconds
        self.run_dir = run_dir
        self.client = httpx.Client(base_url=self.base_url, timeout=30.0)
        self.headers: dict[str, str] = {}

    def close(self) -> None:
        self.client.close()

    def request(self, method: str, path: str, expected_status: int | None = None, **kwargs: Any) -> httpx.Response:
        headers = dict(self.headers)
        headers.update(kwargs.pop("headers", {}))
        response = self.client.request(method, path, headers=headers, **kwargs)
        if expected_status is not None:
            if response.status_code != expected_status:
                raise RuntimeError(f"{method} {path} expected {expected_status}, got {response.status_code}: {self.error_detail(response)}")
            return response
        if response.status_code >= 400:
            raise RuntimeError(f"{method} {path} failed with {response.status_code}: {self.error_detail(response)}")
        return response

    def error_detail(self, response: httpx.Response) -> Any:
        try:
            return response.json()
        except ValueError:
            return response.text

    def login(self) -> None:
        response = self.request("POST", "/api/auth/login", json={"username": self.username, "password": self.password})
        self.headers = {"Authorization": f"Bearer {response.json()['token']}"}

    def create_project(self, stamp: str) -> dict[str, Any]:
        return self.request(
            "POST",
            "/api/projects",
            json={
                "name": f"Task Retry E2E {stamp}",
                "shipNo": f"RETRY-{stamp}",
                "owner": "Automated Acceptance",
                "description": "Generated by tools/run_task_retry_e2e.py",
            },
        ).json()

    def create_drawing(self, project_id: str, stamp: str) -> dict[str, Any]:
        return self.request(
            "POST",
            "/api/drawings",
            json={
                "projectId": project_id,
                "drawingNo": f"RETRY-HULL-{stamp}",
                "title": "Retry Failure Boundary Probe",
                "discipline": "Hull Structure",
            },
        ).json()

    def upload_version(self, drawing_id: str, version_no: str, file_path: Path) -> dict[str, Any]:
        with file_path.open("rb") as file:
            return self.request(
                "POST",
                "/api/versions/upload",
                data={"drawingId": drawing_id, "versionNo": version_no},
                files={"file": (file_path.name, file, "application/dxf")},
            ).json()

    def create_review_task(self, version_id: str) -> dict[str, Any]:
        return self.request("POST", "/api/review-tasks", json={"versionId": version_id}).json()

    def retry_review_task(self, task_id: str, expected_status: int | None = None) -> dict[str, Any]:
        response = self.request("POST", f"/api/review-tasks/{task_id}/retry", expected_status=expected_status)
        return response.json() if response.content else {}

    def get_task(self, task_id: str) -> dict[str, Any]:
        return self.request("GET", f"/api/review-tasks/{task_id}").json()

    def wait_for_task(self, task_id: str) -> dict[str, Any]:
        deadline = time.time() + self.poll_seconds
        last_task: dict[str, Any] | None = None
        while time.time() < deadline:
            task = self.get_task(task_id)
            last_task = task
            if task.get("status") in {"FINISHED", "FAILED"}:
                return task
            time.sleep(1.0)
        raise TimeoutError(f"Review task {task_id} did not finish in {self.poll_seconds}s. Last task={last_task}")

    def task_steps(self, task_id: str) -> list[dict[str, Any]]:
        return self.request("GET", f"/api/review-tasks/{task_id}/steps").json()

    def audit_logs(self, action: str) -> list[dict[str, Any]]:
        page = self.request(
            "GET",
            "/api/audit-logs",
            params={"action": action, "targetType": "task", "size": 100},
        ).json()
        return page.get("items") or []

    def run(self, valid_sample: Path) -> tuple[dict[str, Any], list[Check]]:
        self.run_dir.mkdir(parents=True, exist_ok=True)
        corrupt_sample = self.run_dir / "corrupt_retry_probe.dxf"
        corrupt_sample.write_text("this is not a valid DXF file\n", encoding="utf-8")

        stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        self.login()
        project = self.create_project(stamp)
        drawing = self.create_drawing(project["id"], stamp)

        bad_version = self.upload_version(drawing["id"], "BAD-1", corrupt_sample)
        failed_task = self.create_review_task(bad_version["id"])
        failed_finished = self.wait_for_task(failed_task["id"])
        failed_steps = self.task_steps(failed_task["id"])

        retry_task = self.retry_review_task(failed_task["id"])
        retry_finished = self.wait_for_task(retry_task["id"])
        retry_steps = self.task_steps(retry_task["id"])

        valid_version = self.upload_version(drawing["id"], "V1", valid_sample)
        valid_task = self.create_review_task(valid_version["id"])
        valid_finished = self.wait_for_task(valid_task["id"])
        valid_steps = self.task_steps(valid_task["id"])
        retry_done_error = self.request("POST", f"/api/review-tasks/{valid_task['id']}/retry", expected_status=400).json()

        retry_audit = self.find_retry_audit(retry_task["id"], failed_task["id"])
        checks = [
            Check("corrupt DXF task failed", failed_finished.get("status") == "FAILED", failed_finished.get("errorMessage") or ""),
            Check("corrupt DXF PARSE step failed", self.step_status(failed_steps, "PARSE") == "FAILED", self.step_message(failed_steps, "PARSE")),
            Check("retry created a new task", retry_task.get("id") != failed_task.get("id"), f"{failed_task.get('id')} -> {retry_task.get('id')}"),
            Check("retry kept the same version", retry_task.get("versionId") == failed_task.get("versionId"), retry_task.get("versionId") or ""),
            Check("retry task failed on the same corrupt DXF", retry_finished.get("status") == "FAILED", retry_finished.get("errorMessage") or ""),
            Check("retry task PARSE step failed", self.step_status(retry_steps, "PARSE") == "FAILED", self.step_message(retry_steps, "PARSE")),
            Check("retry audit was recorded", retry_audit is not None, json.dumps(retry_audit or {}, ensure_ascii=False)),
            Check("valid sample task finished", valid_finished.get("status") == "FINISHED", valid_finished.get("errorMessage") or ""),
            Check("valid sample PARSE step succeeded", self.step_status(valid_steps, "PARSE") == "SUCCESS", self.step_message(valid_steps, "PARSE")),
            Check("finished task retry rejected", "FAILED" in (retry_done_error.get("message") or ""), retry_done_error.get("message") or ""),
        ]
        result = {
            "project": project,
            "drawing": drawing,
            "corruptSample": str(corrupt_sample),
            "validSample": str(valid_sample),
            "badVersion": bad_version,
            "failedTask": failed_finished,
            "failedSteps": failed_steps,
            "retryTask": retry_finished,
            "retrySteps": retry_steps,
            "retryAudit": retry_audit,
            "validVersion": valid_version,
            "validTask": valid_finished,
            "validSteps": valid_steps,
            "finishedRetryError": retry_done_error,
        }
        return result, checks

    def find_retry_audit(self, retry_task_id: str, source_task_id: str) -> dict[str, Any] | None:
        for log in self.audit_logs("REVIEW_RETRY"):
            if log.get("targetId") != retry_task_id:
                continue
            detail = parse_json(log.get("detailJson"))
            if detail.get("sourceTaskId") == source_task_id:
                return log
        return None

    def step_status(self, steps: list[dict[str, Any]], code: str) -> str:
        step = next((item for item in steps if item.get("stepCode") == code), None)
        return "" if step is None else str(step.get("status") or "")

    def step_message(self, steps: list[dict[str, Any]], code: str) -> str:
        step = next((item for item in steps if item.get("stepCode") == code), None)
        return "" if step is None else str(step.get("message") or "")


def parse_json(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if not value:
        return {}
    try:
        parsed = json.loads(value)
    except (TypeError, ValueError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def md_escape(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def md_table(headers: list[str], rows: list[list[Any]]) -> str:
    lines = [
        "| " + " | ".join(md_escape(header) for header in headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    lines.extend("| " + " | ".join(md_escape(cell) for cell in row) + " |" for row in rows)
    return "\n".join(lines)


def write_summary(output: Path, result: dict[str, Any], checks: list[Check]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    check_rows = [[check.name, "PASS" if check.ok else "FAIL", check.detail] for check in checks]
    task_rows = [
        ["Failed source", result["failedTask"].get("id"), result["failedTask"].get("status"), result["failedTask"].get("stage"), result["failedTask"].get("errorMessage")],
        ["Retry", result["retryTask"].get("id"), result["retryTask"].get("status"), result["retryTask"].get("stage"), result["retryTask"].get("errorMessage")],
        ["Valid finished", result["validTask"].get("id"), result["validTask"].get("status"), result["validTask"].get("stage"), result["validTask"].get("errorMessage")],
    ]
    step_rows: list[list[Any]] = []
    for label, steps in [("Failed source", result["failedSteps"]), ("Retry", result["retrySteps"]), ("Valid finished", result["validSteps"])]:
        for step in sorted(steps, key=lambda item: item.get("stepOrder", 0)):
            step_rows.append([label, step.get("stepOrder"), step.get("stepCode"), step.get("status"), step.get("message") or ""])

    output.write_text(
        "\n\n".join(
            [
                "# ShipCAD Task Retry E2E",
                f"- Generated at: {datetime.now(timezone.utc).isoformat()}",
                f"- Project: `{result['project']['id']}`",
                f"- Drawing: `{result['drawing']['id']}`",
                f"- Corrupt sample: `{result['corruptSample']}`",
                f"- Valid sample: `{result['validSample']}`",
                "## Checks\n" + md_table(["Check", "Result", "Detail"], check_rows),
                "## Tasks\n" + md_table(["Case", "Task ID", "Status", "Stage", "Error"], task_rows),
                "## Task Steps\n" + md_table(["Case", "Order", "Code", "Status", "Message"], step_rows),
                "## Retry Audit\n\n```json\n" + json.dumps(result["retryAudit"], ensure_ascii=False, indent=2) + "\n```",
                "## Finished Retry Rejection\n\n```json\n" + json.dumps(result["finishedRetryError"], ensure_ascii=False, indent=2) + "\n```",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def print_results(result: dict[str, Any], checks: list[Check], output: Path) -> None:
    print("\nShipCAD task retry E2E")
    print("-" * 88)
    print(f"Project ID      : {result['project']['id']}")
    print(f"Drawing ID      : {result['drawing']['id']}")
    print(f"Failed task     : {result['failedTask']['id']} ({result['failedTask']['status']})")
    print(f"Retry task      : {result['retryTask']['id']} ({result['retryTask']['status']})")
    print(f"Valid task      : {result['validTask']['id']} ({result['validTask']['status']})")
    print(f"Summary         : {output}")
    print("-" * 88)
    for check in checks:
        status = "PASS" if check.ok else "FAIL"
        print(f"{status:4} {check.name} {check.detail}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate review task failure and retry behavior against a live backend.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8080", help="Spring Boot API base URL")
    parser.add_argument("--username", default="admin")
    parser.add_argument("--password", default="admin123")
    parser.add_argument("--valid-sample", type=Path, default=DEFAULT_VALID_SAMPLE)
    parser.add_argument("--poll-seconds", type=int, default=45)
    parser.add_argument("--output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    valid_sample = args.valid_sample.resolve()
    if not valid_sample.exists():
        print(f"Valid DXF sample not found: {valid_sample}", file=sys.stderr)
        return 2
    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    output = (args.output or (DEFAULT_OUTPUT_DIR / f"task-retry-e2e-{stamp}.md")).resolve()
    runner = TaskRetryE2E(args.base_url, args.username, args.password, args.poll_seconds, output.parent)
    try:
        result, checks = runner.run(valid_sample)
    except Exception as exc:
        print(f"Task retry E2E failed: {exc}", file=sys.stderr)
        return 1
    finally:
        runner.close()

    write_summary(output, result, checks)
    print_results(result, checks, output)
    return 0 if all(check.ok for check in checks) else 1


if __name__ == "__main__":
    raise SystemExit(main())
