from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "datasets" / "rules" / "expected.json"


@dataclass
class CaseResult:
    case_id: str
    ok: bool
    expected_rules: list[str]
    actual_rules: list[str]
    message: str


class GoldenE2E:
    def __init__(self, base_url: str, username: str, password: str, poll_seconds: int) -> None:
        self.base_url = base_url.rstrip("/")
        self.username = username
        self.password = password
        self.poll_seconds = poll_seconds
        self.client = httpx.Client(base_url=self.base_url, timeout=30.0)
        self.headers: dict[str, str] = {}

    def close(self) -> None:
        self.client.close()

    def request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        headers = dict(self.headers)
        headers.update(kwargs.pop("headers", {}))
        response = self.client.request(method, path, headers=headers, **kwargs)
        if response.status_code >= 400:
            try:
                detail = response.json()
            except ValueError:
                detail = response.text
            raise RuntimeError(f"{method} {path} failed with {response.status_code}: {detail}")
        return response

    def login(self) -> None:
        response = self.request("POST", "/api/auth/login", json={"username": self.username, "password": self.password})
        token = response.json()["token"]
        self.headers = {"Authorization": f"Bearer {token}"}

    def create_project(self) -> dict[str, Any]:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        return self.request(
            "POST",
            "/api/projects",
            json={
                "name": f"Golden Dataset E2E {stamp}",
                "shipNo": f"GOLDEN-{stamp}",
                "owner": "Automated Acceptance",
                "description": "Generated by tools/run_golden_e2e.py",
            },
        ).json()

    def create_drawing(self, project_id: str, case: dict[str, Any]) -> dict[str, Any]:
        return self.request(
            "POST",
            "/api/drawings",
            json={
                "projectId": project_id,
                "drawingNo": case["drawingNo"],
                "title": case["title"],
                "discipline": "Hull Structure",
            },
        ).json()

    def upload_version(self, drawing_id: str, case: dict[str, Any], file_path: Path) -> dict[str, Any]:
        with file_path.open("rb") as file:
            response = self.request(
                "POST",
                "/api/versions/upload",
                data={"drawingId": drawing_id, "versionNo": case["versionNo"]},
                files={"file": (file_path.name, file, "application/dxf")},
            )
        return response.json()

    def create_review_task(self, version_id: str) -> dict[str, Any]:
        return self.request("POST", "/api/review-tasks", json={"versionId": version_id}).json()

    def create_report(self, task_id: str) -> dict[str, Any]:
        return self.request("POST", "/api/reports", json={"taskId": task_id}).json()

    def wait_for_task(self, task_id: str) -> dict[str, Any]:
        deadline = time.time() + self.poll_seconds
        last_task: dict[str, Any] | None = None
        while time.time() < deadline:
            task = self.request("GET", f"/api/review-tasks/{task_id}").json()
            last_task = task
            if task["status"] in {"FINISHED", "FAILED"}:
                return task
            time.sleep(1.0)
        raise TimeoutError(f"Review task {task_id} did not finish in {self.poll_seconds}s. Last task={last_task}")

    def issues(self, task_id: str) -> list[dict[str, Any]]:
        return self.request("GET", "/api/issues", params={"taskId": task_id}).json()

    def entities(self, version_id: str) -> list[dict[str, Any]]:
        return self.request("GET", f"/api/versions/{version_id}/entities").json()

    def versions(self) -> list[dict[str, Any]]:
        return self.request("GET", "/api/versions").json()

    def file_head_check(self, version_id: str) -> None:
        response = self.request("GET", f"/api/versions/{version_id}/file")
        if len(response.content) == 0:
            raise AssertionError("version file endpoint returned an empty body")

    def run_case(self, project_id: str, manifest_dir: Path, case: dict[str, Any]) -> CaseResult:
        case_id = case["id"]
        expected_rules = sorted(case.get("expectedRuleCodes", []))
        try:
            file_path = (manifest_dir / case["file"]).resolve()
            if not file_path.exists():
                raise FileNotFoundError(file_path)
            drawing = self.create_drawing(project_id, case)
            version = self.upload_version(drawing["id"], case, file_path)
            self.file_head_check(version["id"])
            task = self.create_review_task(version["id"])
            finished = self.wait_for_task(task["id"])
            if finished["status"] != "FINISHED":
                raise AssertionError(f"review task failed: {finished.get('errorMessage')}")

            actual_issues = self.issues(task["id"])
            actual_rules = sorted({issue["ruleCode"] for issue in actual_issues})
            self.assert_rules(case, expected_rules, actual_rules)
            self.assert_parser_expectations(version["id"], case.get("parserExpectations", {}))
            self.assert_issue_evidence(version["id"], case, actual_issues)
            report = self.create_report(task["id"])
            self.assert_report(case, actual_issues, report)
            return CaseResult(case_id, True, expected_rules, actual_rules, "ok")
        except Exception as exc:
            return CaseResult(case_id, False, expected_rules, [], str(exc))

    def assert_rules(self, case: dict[str, Any], expected_rules: list[str], actual_rules: list[str]) -> None:
        if case.get("allowUnexpectedRuleCodes", False):
            missing = sorted(set(expected_rules) - set(actual_rules))
            if missing:
                raise AssertionError(f"missing expected rule codes: {missing}; actual={actual_rules}")
            return
        if actual_rules != expected_rules:
            raise AssertionError(f"expected rule codes {expected_rules}, got {actual_rules}")

    def assert_issue_evidence(self, version_id: str, case: dict[str, Any], issues: list[dict[str, Any]]) -> None:
        parsed_entities = {entity["id"]: entity for entity in self.entities(version_id)}
        for issue in issues:
            entity_ref = issue.get("entityRef") or ""
            if entity_ref and entity_ref not in parsed_entities:
                raise AssertionError(f"issue {issue['id']} references missing entityRef={entity_ref}")
            evidence_items = issue.get("evidences") or []
            evidence_types = {item.get("evidenceType") for item in evidence_items}
            if "RULE_RESULT" not in evidence_types:
                raise AssertionError(f"issue {issue['id']} is missing RULE_RESULT evidence")
            if "KNOWLEDGE_CLAUSE" not in evidence_types:
                raise AssertionError(f"issue {issue['id']} is missing KNOWLEDGE_CLAUSE evidence")

        expected_evidence = case.get("expectedEvidence") or {}
        if not expected_evidence:
            return
        issues_by_rule: dict[str, list[dict[str, Any]]] = {}
        for issue in issues:
            issues_by_rule.setdefault(issue["ruleCode"], []).append(issue)

        for rule_code, expected in expected_evidence.items():
            candidates = issues_by_rule.get(rule_code) or []
            if not candidates:
                raise AssertionError(f"no issue found for expected evidence rule {rule_code}")
            issue = candidates[0]
            expected_layer = expected.get("layerName")
            if expected_layer is not None and issue.get("layerName") != expected_layer:
                raise AssertionError(f"{rule_code} expected layerName={expected_layer}, got {issue.get('layerName')}")

            entity_ref = issue.get("entityRef") or ""
            if expected.get("requireEntityRef") and not entity_ref:
                raise AssertionError(f"{rule_code} expected a non-empty entityRef")
            if entity_ref:
                entity = parsed_entities[entity_ref]
                if expected_layer is not None and entity.get("layerName") != expected_layer:
                    raise AssertionError(f"{rule_code} entityRef layer mismatch: expected {expected_layer}, got {entity.get('layerName')}")
                self.assert_embedded_evidence(issue, "CAD_ENTITY", entity_ref)
            elif expected_layer is not None:
                self.assert_embedded_evidence(issue, "CAD_LAYER", expected_layer)

    def assert_embedded_evidence(self, issue: dict[str, Any], evidence_type: str, source_id: str) -> None:
        matches = [
            evidence
            for evidence in (issue.get("evidences") or [])
            if evidence.get("evidenceType") == evidence_type and evidence.get("sourceId") == source_id
        ]
        if not matches:
            raise AssertionError(f"{issue['ruleCode']} expected {evidence_type} evidence with sourceId={source_id}")

    def assert_parser_expectations(self, version_id: str, expectations: dict[str, Any]) -> None:
        version = next((item for item in self.versions() if item["id"] == version_id), None)
        if not version:
            raise AssertionError(f"version {version_id} not found after review")
        summary = json.loads(version.get("parseSummaryJson") or "{}")
        min_entities = expectations.get("minEntityCount")
        if min_entities is not None and summary.get("entityCount", 0) < min_entities:
            raise AssertionError(f"entityCount {summary.get('entityCount')} < {min_entities}")
        layers = set(summary.get("layers") or [])
        missing_layers = sorted(set(expectations.get("requiredLayers") or []) - layers)
        if missing_layers:
            raise AssertionError(f"missing parsed layers: {missing_layers}")
        blocks = set(summary.get("blocks") or [])
        missing_blocks = sorted(set(expectations.get("requiredBlocks") or []) - blocks)
        if missing_blocks:
            raise AssertionError(f"missing parsed blocks: {missing_blocks}")
        type_counts = summary.get("typeCounts") or {}
        missing_types = sorted(
            entity_type
            for entity_type in (expectations.get("requiredEntityTypes") or [])
            if type_counts.get(entity_type, 0) <= 0
        )
        if missing_types:
            raise AssertionError(f"missing parsed entity types: {missing_types}; typeCounts={type_counts}")

    def assert_report(self, case: dict[str, Any], issues: list[dict[str, Any]], report: dict[str, Any]) -> None:
        content = report.get("content") or ""
        if "解析证据摘要" not in content:
            raise AssertionError("report is missing parser evidence summary")
        if "问题证据详情" not in content:
            raise AssertionError("report is missing issue evidence details")
        expected_rules = case.get("expectedRuleCodes") or []
        if not expected_rules and "未发现当前规则集命中的问题" not in content:
            raise AssertionError("clean report is missing no-issue summary")
        for rule_code in expected_rules:
            if rule_code not in content:
                raise AssertionError(f"report is missing expected rule code {rule_code}")
        for issue in issues:
            entity_ref = issue.get("entityRef") or ""
            if entity_ref and f"entityRef={entity_ref}" not in content:
                raise AssertionError(f"report is missing entity evidence {entity_ref}")
            layer_name = issue.get("layerName") or ""
            if layer_name and layer_name not in content:
                raise AssertionError(f"report is missing layer evidence {layer_name}")


def load_manifest(path: Path) -> list[dict[str, Any]]:
    return json.loads(path.read_text(encoding="utf-8"))


def print_results(results: list[CaseResult]) -> None:
    print("\nGolden dataset E2E results")
    print("-" * 88)
    for result in results:
        status = "PASS" if result.ok else "FAIL"
        print(f"{status:4} {result.case_id:24} expected={result.expected_rules} actual={result.actual_rules} {result.message}")
    print("-" * 88)
    passed = sum(1 for result in results if result.ok)
    print(f"{passed}/{len(results)} cases passed")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run the DXF golden dataset against the live backend and CAD worker.")
    parser.add_argument("--base-url", default="http://127.0.0.1:8080", help="Spring Boot API base URL")
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Golden dataset manifest path")
    parser.add_argument("--username", default="admin")
    parser.add_argument("--password", default="admin123")
    parser.add_argument("--poll-seconds", type=int, default=45)
    parser.add_argument("--keep-going", action="store_true", help="Run remaining cases after a failure")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_path = args.manifest.resolve()
    cases = load_manifest(manifest_path)
    runner = GoldenE2E(args.base_url, args.username, args.password, args.poll_seconds)
    results: list[CaseResult] = []
    try:
        runner.login()
        project = runner.create_project()
        for case in cases:
            result = runner.run_case(project["id"], manifest_path.parent, case)
            results.append(result)
            if not result.ok and not args.keep_going:
                break
    except Exception as exc:
        print(f"Golden dataset E2E setup failed: {exc}", file=sys.stderr)
        return 2
    finally:
        runner.close()

    print_results(results)
    return 0 if results and all(result.ok for result in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
